### ISSUE TITLE
TextInside function possible bug

### ISSUE THREAD

**Issue by mainleigh** [magnusdv/pedsuite#1]
Hi! I am using pedtools in R to help create some of the sub-pedigrees I'm working with to help with linkage for preserved cognitive function while aging. There is a 'textInside' option when plotting the pedigrees, however, these seem to come out in random order and there is little way to predict which person gets which text besides adding one by one. As I am trying to add ages inside the individuals, this ended up being a nightmare in which I thought I had done the ages wrong for my entire analysis (luckily I did not, but just a warning for those who try it)! 

Below is a picture of what I had originally - blue is for those who have preserved cognition, red are those with dementia, and blank are unknown (all unknown should have an 'x' for the age). All the blue and red should have ages, but as you can see it lines them up (what seems to be) randomly. To assign ages I grabbed it directly from the file I was plotting with "textInside = table_name$age_column" and this does not print them to the assigned IDs or in order:

![image](https://user-images.githubusercontent.com/31222644/128916251-df282841-be69-458d-93b4-271f483478ee.png)

I did try work arounds to this issues as creating ages as a marker or changing the IDs to ages, but obviously neither of these worked. Is this a bug that is easily fixable on either of our ends (as I simply could be doing something wrong)? Or should I find a different package that can fit my needs better? Since I have been struggling with this I thought I'd reach out since I'm sure it is an issue you are not familiar with! I really like how pedtools graphs these pedigrees so I would hate to change software, but without proper age assignment (as if I had to do list ages manually for all 200+ pedigrees I have) it is hard for me to use.

As I will be continuously working on this for a while, I will keep you updated if I do find a solution! Let me know if you need anymore information or code from my end. Thanks for your help!

**Comment by magnusdv** [comment]
My guess is that your pedigree has been reordered, typically during creation. For example, if you used the `ped()` function, this by default reorders the individuals so that parents precede their children. 

Without knowing your code it is hard to recommend a fix, but here are a few suggestions you can try:
1. Add `reorder = FALSE` when creating the pedigree
2. Reorder the ages to match the new order
3. If your data frame is already in correct pedigree format, use `as.ped()` which does not reorder by default.

### Code example

``` r
library(pedtools)

# Data frame with pedigree and age info. Note: nonstandard order!
df = data.frame(id = 5:1, 
                fid = c(3,0,1,0,0), 
                mid = c(4,0,2,0,0),
                sex = c(1,2,1,2,1), 
                age = c(10, "x", 35,"x", "x"))
df
#>   id fid mid sex age
#> 1  5   3   4   1  10
#> 2  4   0   0   2   x
#> 3  3   1   2   1  35
#> 4  2   0   0   2   x
#> 5  1   0   0   1   x

# Create ped with default reordering
x = ped(id = df$id, fid = df$fid, mid = df$mid, sex = df$sex)

# This gives wrong ages!
plo(x, textInside = df$age)
```

<img src="https://i.imgur.com/LsxcjnO.png" style="display: block; margin: auto;" />

 **Solution 1:** Reorder the age vector
``` r
newage = df$age[match(labels(x), df$id)]
plot(x, textInside = newage)
```

<img src="https://i.imgur.com/6UzwF4I.png" style="display: block; margin: auto;" />

**Solution 2:** `reorder = FALSE`
``` r
y = ped(id = df$id, fid = df$fid, mid = df$mid, sex = df$sex, 
        reorder = FALSE)
plot(y, textInside = df$age)
```

<img src="https://i.imgur.com/2h4WZK7.png" style="display: block; margin: auto;" />

 **Solution 3:** `as.ped()`
``` r
z = as.ped(df[1:4])
plot(z, textInside = df$age)
```

<img src="https://i.imgur.com/2h4WZK7.png" style="display: block; margin: auto;" />

<sup>Created on 2021-08-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
